# This dockerfile provides an example of using the production image in a working stack
version: '2'

services:

  mysql:
    image: mysql:5.6
    hostname: mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: semaphore
      MYSQL_USER: semaphore
      MYSQL_PASSWORD: hx4hjxqthfwbfsy5535u4agfdscm

  semaphore:
    image: semaphoreui/semaphore:prod-compose
    build:
      context: ./../../../
      dockerfile: ./deployment/docker/prod/Dockerfile
    # volumes:
    #   - /path/to/local/requirements.txt:/etc/semaphore/requirements.txt
    environment:
      SEMAPHORE_DB_DIALECT: mysql
      SEMAPHORE_DB_USER: semaphore
      SEMAPHORE_DB_PASS: hx4hjxqthfwbfsy5535u4agfdscm
      SEMAPHORE_DB_HOST: mysql
      SEMAPHORE_DB_PORT: 3306
      SEMAPHORE_DB: semaphore
      SEMAPHORE_ADMIN_PASSWORD: cangetin
      SEMAPHORE_ADMIN_NAME: admin
      SEMAPHORE_ADMIN_EMAIL: admin@localhost
      SEMAPHORE_ADMIN: admin
    depends_on:
      - mysql
  semaphore_proxy:
    image: ansiblesemaphore/proxy:latest
    build:
      context: ./proxy
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - semaphore
