file:
  /usr/local/bin/semaphore-wrapper:
    exists: true
    owner: semaphore
    group: root
    filetype: file
  /usr/local/bin/semaphore:
    exists: true
    owner: semaphore
    group: root
    filetype: file
package:
  ansible:
    installed: true
  curl:
    installed: true
  git:
    installed: true
  go:
    installed: false
  libc-dev:
    installed: false
  mysql-client:
    installed: true
  nodejs:
    installed: false
  openssh-client:
    installed: true
  tini:
    installed: true
user:
  semaphore:
    exists: true
    uid: 1001
    gid: 0
    home: /home/semaphore
command:
  semaphore:
    exit-status: 1
    stdout:
    - Cannot Find configuration! Use -config parameter to point to a JSON file generated
      by -setup.
    - 'Hint: have you run `-setup` ?'
    timeout: 10000
