redis:
  name: redis:latest
  image: redis
  expose:
    - 6379
  volumes:
    - /tmp/redis:/data

mongodb:
  image: mongo:latest
  command: mongod --smallfiles --directoryperdb --noprealloc
  hostname: mongodb
  volumes:
    - /tmp/mongodb:/data/db
  expose:
    - 27017