[[constraint]]
  name = "github.com/Sirupsen/logrus"
  version = "1.0.4"

[[constraint]]
  name = "github.com/go-sql-driver/mysql"
  version = "1.3.0"

[[constraint]]
  name = "github.com/gobuffalo/packr"
  version = "1.10.4"

[[constraint]]
  name = "github.com/google/go-github"
  version = "15.0.0"

[[constraint]]
  name = "github.com/gorilla/context"
  version = "1.1.0"

[[constraint]]
  name = "github.com/gorilla/handlers"
  version = "1.3.0"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.7.3"

[[constraint]]
  name = "github.com/gorilla/securecookie"
  version = "1.1.1"

[[constraint]]
  name = "github.com/gorilla/websocket"
  version = "1.2.0"

[[constraint]]
  name = "github.com/masterminds/squirrel"
  version = "1.0.0"

[[constraint]]
  name = "github.com/russross/blackfriday"
  version = "1.5.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[constraint]]
  name = "gopkg.in/gorp.v1"
  version = "1.7.1"

[[constraint]]
  name = "gopkg.in/ldap.v2"
  version = "2.5.1"

[prune]
  go-tests = true
  unused-packages = true
