name: Release
on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/setup-go@v3
        with: { go-version: 1.18 }

      - uses: actions/setup-node@v3
        with: { node-version: '16' }

      - run: go install github.com/go-task/task/v3/cmd/task@latest

      - run: sudo apt update && sudo apt-get install rpm

      - uses: actions/checkout@v3

      - run: task deps

      - run: |
        echo ${{ secrets.GPG_KEY }} | tr " " "\n" | base64 -d | gpg --import --batch
        gpg --sign -u "${{ secrets.GPG_PUB }}" --pinentry-mode loopback --yes --batch --passphrase "${{ secrets.GPG_PASS }}" --output unlock.sig --detach-sign README.md
        rm -f unlock.sig

      - run:  git reset --hard

      - run: GITHUB_TOKEN=${{ secrets.GH_TOKEN }} task release:prod


  deploy-prod:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/setup-go@v3
        with: { go-version: 1.18 }

      - run: go install github.com/go-task/task/v3/cmd/task@latest

      - uses: actions/checkout@v3

      - run: context=prod task docker:test

      - uses: docker/setup-qemu-action@v2

      - uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          file: ./deployment/docker/prod/buildx.Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USER }}/semaphore:latest,${{ secrets.DOCKER_USER }}/semaphore:${{ github.ref_name }}
