name: Test
on:
  push:
    branches:
    - test

jobs:
  test-integration:
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/setup-go@v3
      with: { go-version: 1.18 }

    - run: go install github.com/go-task/task/v3/cmd/task@latest

    - uses: actions/checkout@v3

    - run: context=ci task dc:up
